import '../../core/constants.dart';
import '../../core/date_time_utils.dart';
import '../../data/models/inspection_enums.dart';
import '../../data/models/inspection_models.dart';
import 'pdf_report_models.dart';

class InspectionReportMapper {
  static InspectionReportData fromInspection(InspectionRecord inspection) {
    return InspectionReportData(
      documentNumber: _pdfSafe(inspection.documentNumber),
      customer: _pdfSafe(inspection.customer),
      workOrderNumber: _pdfSafe(inspection.workOrderNumber),
      customerReference: _pdfSafe(inspection.customerReference),
      assetName: _pdfSafe(inspection.assetName),
      siteLocation: _pdfSafe(inspection.siteLocation),
      technicianName: _pdfSafe(inspection.technicianName),
      servicingShop: _pdfSafe(inspection.servicingShop),
      inspectionDateTime: inspection.inspectionDateTime,
      createdAt: inspection.createdAt,
      completedAt: inspection.completedAt,
      emailedAt: inspection.emailedAt,
      status: _mapStatus(inspection.status),
      finalTechComments: _pdfSafeNullable(inspection.finalTechComments),
      criticalAcknowledged: inspection.criticalAcknowledged,
      signature: (inspection.signatureFilePath ?? '').trim().isEmpty
          ? null
          : InspectionReportSignature(
              filePath: inspection.signatureFilePath,
              signerName: _pdfSafe(inspection.technicianName),
              signedAt: inspection.completedAt ?? inspection.updatedAt,
            ),
      actionItems: inspection.actionItems
          .map(
            (ActionItem item) => InspectionReportActionItem(
              title: _pdfSafe(item.title),
              description: _pdfSafe(item.description),
              sourceSection: item.sourceSectionKey == null
                  ? null
                  : _pdfSafe(
                      InspectionSectionKeys.titleFor(item.sourceSectionKey!),
                    ),
              sourceItem: item.sourceItemKey == null
                  ? null
                  : _pdfSafe(_labelForItem(inspection, item.sourceItemKey!)),
              partsRequired: _pdfSafeNullable(item.partsRequired),
              isAutoGenerated: item.isAutoGenerated,
              conditionRating: _mapCondition(item.conditionRating),
            ),
          )
          .toList(growable: false),
      sections: <InspectionReportSection>[
        InspectionReportSection(
          key: InspectionSectionKeys.jobAssetIdentification,
          title: 'Job & Asset Identification',
          subtitle: 'Header details and as-found photos.',
          items: <InspectionReportItem>[
            InspectionReportItem(
              label: 'Inspection details',
              value: <String>[
                'Customer: ${inspection.customer}',
                'HPU Asset ID / Name: ${inspection.hpuAssetIdName}',
                'Asset / equipment: ${inspection.assetName}',
                'Work order: ${inspection.workOrderNumber}',
                'Customer reference / PO / job number: ${inspection.customerReference}',
                'Location / site: ${inspection.siteLocation}',
                'Technician: ${inspection.technicianName}',
                'Servicing shop: ${inspection.servicingShop}',
                'Inspection date/time: ${_reportDateTime(inspection.inspectionDateTime)}',
              ].map(_pdfSafe).join('\n'),
              photos: _photosForItem(
                inspection,
                InspectionSectionKeys.jobAssetIdentification,
                InspectionItemKeys.overviewPhotos,
                'HPU Unit wide shot',
              ),
            ),
          ],
        ),
        InspectionReportSection(
          key: InspectionSectionKeys.componentTracking,
          title: 'Component Tracking',
          subtitle: 'Component details and nameplate photos.',
          items: inspection.componentEntries
              .map(
                (ComponentEntry entry) => InspectionReportItem(
                  label: entry.componentType,
                  value: <String>[
                    'Model / part number: ${_orNotRecorded(entry.modelPartNumber)}',
                    'Serial number: ${_orNotRecorded(entry.serialNumber)}',
                    if ((entry.notes ?? '').trim().isNotEmpty)
                      'Notes: ${_pdfSafe(entry.notes!.trim())}',
                  ].join('\n'),
                  conditionRating: _mapCondition(entry.conditionRating),
                  comment: _pdfSafeNullable(entry.notes),
                  photos: _photosForItem(
                    inspection,
                    InspectionSectionKeys.componentTracking,
                    'component:${entry.id}',
                    entry.componentType,
                  ),
                ),
              )
              .toList(growable: false),
        ),
        InspectionReportSection(
          key: InspectionSectionKeys.fluidTankService,
          title: 'Fluid & Tank Service',
          items: <InspectionReportItem>[
            _responseItem(
              inspection,
              InspectionSectionKeys.fluidTankService,
              InspectionItemKeys.fluidLevel,
              'Fluid Level',
            ),
            _responseItem(
              inspection,
              InspectionSectionKeys.fluidTankService,
              InspectionItemKeys.fluidClarity,
              'Fluid Clarity',
            ),
            _responseItem(
              inspection,
              InspectionSectionKeys.fluidTankService,
              InspectionItemKeys.tankIntegrity,
              'Tank Integrity',
            ),
            _responseItem(
              inspection,
              InspectionSectionKeys.fluidTankService,
              InspectionItemKeys.tankCleanoutPerformed,
              'Tank Cleanout Performed',
            ),
          ],
        ),
        InspectionReportSection(
          key: InspectionSectionKeys.hoseConnectionInspection,
          title: 'Hose & Connection Inspection',
          subtitle:
              'Identify the hose, failure type, and parts needed to build the replacement.',
          items: <InspectionReportItem>[
            _responseItem(
              inspection,
              InspectionSectionKeys.hoseConnectionInspection,
              InspectionItemKeys.overallHoseCondition,
              'Overall Hose Condition',
            ),
            ...inspection.hoseEntries.map(
              (HoseEntry entry) => InspectionReportItem(
                label: (entry.hoseNameLocation ?? '').trim().isEmpty
                    ? 'Hose issue'
                    : _pdfSafe(entry.hoseNameLocation!),
                value: <String>[
                  'Failure type: ${entry.failureType?.label ?? 'Not recorded'}',
                  'Hose size: ${_orNotRecorded(entry.hoseSize)}',
                  'Hose length: ${_orNotRecorded(entry.hoseLength)}',
                  'Fitting / end A: ${_orNotRecorded(entry.fittingEndA)}',
                  'Fitting / end B: ${_orNotRecorded(entry.fittingEndB)}',
                  'Replacement parts needed: ${_orNotRecorded(entry.replacementPartNumbers)}',
                  'Notes: ${_orNotRecorded(entry.notes)}',
                ].join('\n'),
                conditionRating: entry.hasFailure
                    ? ReportConditionRating.unsatisfactory
                    : null,
                comment: _pdfSafeNullable(entry.notes),
                photos: _photosForItem(
                  inspection,
                  InspectionSectionKeys.hoseConnectionInspection,
                  'hose:${entry.id}',
                  (entry.hoseNameLocation ?? '').trim().isEmpty
                      ? 'Hose issue'
                      : _pdfSafe(entry.hoseNameLocation!),
                ),
                helperText:
                    'Identify the hose, failure type, and parts needed to build the replacement.',
              ),
            ),
          ],
        ),
        InspectionReportSection(
          key: InspectionSectionKeys.filtrationBreatherService,
          title: 'Filtration & Breather Service',
          items: <InspectionReportItem>[
            _responseItem(
              inspection,
              InspectionSectionKeys.filtrationBreatherService,
              InspectionItemKeys.breatherPartNumber,
              'Breather Part Number',
            ),
            _responseItem(
              inspection,
              InspectionSectionKeys.filtrationBreatherService,
              InspectionItemKeys.breatherReplaced,
              'Breather Replaced',
            ),
            _responseItem(
              inspection,
              InspectionSectionKeys.filtrationBreatherService,
              InspectionItemKeys.pressureFilterPartNumber,
              'Pressure Filter PN',
            ),
            _responseItem(
              inspection,
              InspectionSectionKeys.filtrationBreatherService,
              InspectionItemKeys.pressureFilterReplaced,
              'Pressure Filter Replaced',
            ),
            _responseItem(
              inspection,
              InspectionSectionKeys.filtrationBreatherService,
              InspectionItemKeys.returnFilterPartNumber,
              'Return Filter PN',
            ),
            _responseItem(
              inspection,
              InspectionSectionKeys.filtrationBreatherService,
              InspectionItemKeys.returnFilterReplaced,
              'Return Filter Replaced',
            ),
            ...inspection.filterEntries.map(
              (FilterEntry entry) => InspectionReportItem(
                label: (entry.filterName ?? '').trim().isEmpty
                    ? 'Filter entry'
                    : _pdfSafe(entry.filterName!),
                value: <String>[
                  'Part number: ${_orNotRecorded(entry.partNumber)}',
                  'Replaced: ${entry.replacedStatus?.label ?? 'Not recorded'}',
                  if ((entry.notes ?? '').trim().isNotEmpty)
                    'Notes: ${_pdfSafe(entry.notes!.trim())}',
                ].join('\n'),
                conditionRating: _mapCondition(entry.conditionRating),
                comment: _pdfSafeNullable(entry.notes),
                photos: _photosForItem(
                  inspection,
                  InspectionSectionKeys.filtrationBreatherService,
                  'filter:${entry.id}',
                  (entry.filterName ?? '').trim().isEmpty
                      ? 'Filter entry'
                      : _pdfSafe(entry.filterName!),
                ),
              ),
            ),
          ],
        ),
        InspectionReportSection(
          key: InspectionSectionKeys.operationalDataSystemTest,
          title: 'Operational Data / System Test',
          items: <InspectionReportItem>[
            _responseItem(
              inspection,
              InspectionSectionKeys.operationalDataSystemTest,
              InspectionItemKeys.equipmentRunning,
              'Equipment running',
            ),
            _responseItem(
              inspection,
              InspectionSectionKeys.operationalDataSystemTest,
              InspectionItemKeys.pumpCompensatorSetting,
              'Pump Compensator Setting Observed',
            ),
            _responseItem(
              inspection,
              InspectionSectionKeys.operationalDataSystemTest,
              InspectionItemKeys.changePumpCompensator,
              'Change Pump Compensator Setting?',
            ),
            _responseItem(
              inspection,
              InspectionSectionKeys.operationalDataSystemTest,
              InspectionItemKeys.systemReliefSetting,
              'System Relief Setting Observed',
            ),
            _responseItem(
              inspection,
              InspectionSectionKeys.operationalDataSystemTest,
              InspectionItemKeys.changeSystemRelief,
              'Change System Relief Setting?',
            ),
            InspectionReportItem(
              label: 'Operating Temperature',
              value:
                  '${_valueFor(inspection, InspectionSectionKeys.operationalDataSystemTest, InspectionItemKeys.operatingTemperature)} ${_temperatureUnitFor(inspection)}'
                      .trim(),
              photos: _photosForItem(
                inspection,
                InspectionSectionKeys.operationalDataSystemTest,
                InspectionItemKeys.operatingTemperature,
                'Operating Temperature',
              ),
            ),
            _responseItem(
              inspection,
              InspectionSectionKeys.operationalDataSystemTest,
              InspectionItemKeys.accumulatorPreCharge,
              'Accumulator Pre-charge',
            ),
            _responseItem(
              inspection,
              InspectionSectionKeys.operationalDataSystemTest,
              InspectionItemKeys.chargeAccumulator,
              'Accumulator needs charge?',
            ),
          ],
        ),
        InspectionReportSection(
          key: InspectionSectionKeys.followUpRepairsQuoting,
          title: 'Follow-Up Repairs & Quoting',
          items: <InspectionReportItem>[
            _responseItem(
              inspection,
              InspectionSectionKeys.followUpRepairsQuoting,
              InspectionItemKeys.additionalPartsRepairs,
              'Additional parts / repairs required',
            ),
            ...inspection.requiredItems.map(
              (RequiredItemEntry entry) => InspectionReportItem(
                label: (entry.itemName ?? '').trim().isEmpty
                    ? 'Required item'
                    : _pdfSafe(entry.itemName!),
                value: <String>[
                  'Quantity: ${entry.quantity ?? 0}',
                  'Part number: ${_orNotRecorded(entry.partNumber)}',
                  'Description: ${_orNotRecorded(entry.description)}',
                  'Related section / item: ${_orNotRecorded(entry.relatedSectionItem)}',
                  'Notes: ${_orNotRecorded(entry.notes)}',
                ].join('\n'),
                comment: _pdfSafeNullable(entry.notes),
                photos: _photosForItem(
                  inspection,
                  InspectionSectionKeys.followUpRepairsQuoting,
                  'required_item:${entry.id}',
                  (entry.itemName ?? '').trim().isEmpty
                      ? 'Required item'
                      : _pdfSafe(entry.itemName!),
                ),
              ),
            ),
            if (inspection.finalTechComments.trim().isNotEmpty)
              InspectionReportItem(
                label: 'Final Tech Comments',
                value: _pdfSafe(inspection.finalTechComments.trim()),
              ),
          ],
        ),
      ],
      branding: const InspectionReportBranding(
        companyName: AppConstants.brandCompanyName,
      ),
    );
  }

  static InspectionReportItem _responseItem(
    InspectionRecord inspection,
    String sectionKey,
    String itemKey,
    String label,
  ) {
    final InspectionResponse? response = inspection.responseByKey(
      sectionKey,
      itemKey,
    );
    return InspectionReportItem(
      label: _pdfSafe(label),
      value: response?.value?.trim().isNotEmpty ?? false
          ? _pdfSafe(response!.value!)
          : 'Not answered',
      conditionRating: _mapCondition(response?.conditionRating),
      comment: _pdfSafeNullable(response?.comment),
      photos: _photosForItem(inspection, sectionKey, itemKey, _pdfSafe(label)),
    );
  }

  static List<InspectionReportPhoto> _photosForItem(
    InspectionRecord inspection,
    String sectionKey,
    String itemKey,
    String label,
  ) {
    return inspection.photos
        .where((InspectionPhoto photo) => photo.itemKey == itemKey)
        .map(
          (InspectionPhoto photo) => InspectionReportPhoto(
            filePath: photo.filePath,
            caption: (photo.caption ?? '').trim().isEmpty
                ? _pdfSafe(label)
                : _pdfSafe(photo.caption!.trim()),
            sectionTitle: _pdfSafe(InspectionSectionKeys.titleFor(sectionKey)),
            itemLabel: _pdfSafe(label),
            capturedAt: photo.capturedAt,
            sortOrder: photo.sortOrder,
          ),
        )
        .toList(growable: false)
      ..sort(
        (InspectionReportPhoto a, InspectionReportPhoto b) =>
            a.sortOrder.compareTo(b.sortOrder),
      );
  }

  static String _valueFor(
    InspectionRecord inspection,
    String sectionKey,
    String itemKey,
  ) {
    final InspectionResponse? response = inspection.responseByKey(
      sectionKey,
      itemKey,
    );
    return _pdfSafe(response?.value ?? '');
  }

  static String _temperatureUnitFor(InspectionRecord inspection) {
    final String value = _valueFor(
      inspection,
      InspectionSectionKeys.operationalDataSystemTest,
      InspectionItemKeys.operatingTemperatureUnit,
    );
    if (value == '°C') {
      return 'deg C';
    }
    if (value == '°F') {
      return 'deg F';
    }
    return value;
  }

  static InspectionReportStatus _mapStatus(InspectionStatus status) {
    switch (status) {
      case InspectionStatus.draft:
        return InspectionReportStatus.draft;
      case InspectionStatus.inProgress:
        return InspectionReportStatus.inProgress;
      case InspectionStatus.complete:
        return InspectionReportStatus.complete;
      case InspectionStatus.emailed:
        return InspectionReportStatus.emailed;
    }
  }

  static ReportConditionRating? _mapCondition(ConditionRating? rating) {
    switch (rating) {
      case null:
        return null;
      case ConditionRating.satisfactory:
        return ReportConditionRating.satisfactory;
      case ConditionRating.monitorAtRisk:
        return ReportConditionRating.monitor;
      case ConditionRating.unsatisfactory:
        return ReportConditionRating.unsatisfactory;
      case ConditionRating.criticalOutOfService:
        return ReportConditionRating.critical;
    }
  }

  static String _labelForItem(InspectionRecord inspection, String itemKey) {
    if (itemKey.startsWith('hose:')) {
      final String hoseId = itemKey.substring('hose:'.length);
      final HoseEntry? hoseEntry = inspection.hoseEntries
          .cast<HoseEntry?>()
          .firstWhere(
            (HoseEntry? entry) => entry?.id == hoseId,
            orElse: () => null,
          );
      return _pdfSafe(hoseEntry?.hoseNameLocation ?? 'Hose entry');
    }
    if (itemKey.startsWith('filter:')) {
      final String filterId = itemKey.substring('filter:'.length);
      final FilterEntry? filterEntry = inspection.filterEntries
          .cast<FilterEntry?>()
          .firstWhere(
            (FilterEntry? entry) => entry?.id == filterId,
            orElse: () => null,
          );
      return _pdfSafe(filterEntry?.filterName ?? 'Filter entry');
    }
    final InspectionResponse? response = inspection.responses
        .cast<InspectionResponse?>()
        .firstWhere(
          (InspectionResponse? entry) => entry?.itemKey == itemKey,
          orElse: () => null,
        );
    return _pdfSafe(response?.itemLabel ?? itemKey.replaceAll('_', ' '));
  }

  static String _orNotRecorded(String? value) {
    return (value ?? '').trim().isEmpty
        ? 'Not recorded'
        : _pdfSafe(value!.trim());
  }

  static String _reportDateTime(DateTime value) {
    return _pdfSafe(DateTimeUtils.displayDateTime(value));
  }

  static String _pdfSafe(String value) {
    return value
        .replaceAll('•', ' - ')
        .replaceAll('°C', 'deg C')
        .replaceAll('°F', 'deg F');
  }

  static String? _pdfSafeNullable(String? value) {
    if (value == null) {
      return null;
    }
    return _pdfSafe(value);
  }
}
